// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaApi.Data;

#nullable disable

namespace MinhaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinhaApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Eletrodomésticos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Informática"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Móveis"
                        });
                });

            modelBuilder.Entity("MinhaApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Nome = "iPhone 15",
                            Preco = 5999.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Nome = "Samsung Galaxy S23",
                            Preco = 3800.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Nome = "Fone Bluetooth Sony",
                            Preco = 1200.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Nome = "Carregador Rápido",
                            Preco = 150.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Nome = "Smartwatch Apple",
                            Preco = 2500.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Nome = "Geladeira Brastemp",
                            Preco = 4200.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Nome = "Micro-ondas LG",
                            Preco = 890.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Nome = "Fogão 4 Bocas",
                            Preco = 1100.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Nome = "Máquina de Lavar 12kg",
                            Preco = 2300.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            Nome = "Aspirador Robô",
                            Preco = 1500.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 3,
                            Nome = "Notebook Dell i7",
                            Preco = 5200.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 3,
                            Nome = "Mouse Gamer Razer",
                            Preco = 450.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 3,
                            Nome = "Monitor LG 29' UltraWide",
                            Preco = 1300.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 3,
                            Nome = "Teclado Mecânico RGB",
                            Preco = 350.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 3,
                            Nome = "Webcam Full HD",
                            Preco = 280.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 4,
                            Nome = "Cadeira Gamer",
                            Preco = 1200.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 4,
                            Nome = "Mesa de Escritório L",
                            Preco = 650.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 4,
                            Nome = "Estante de Livros",
                            Preco = 300.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 4,
                            Nome = "Luminária de Mesa",
                            Preco = 85.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 4,
                            Nome = "Suporte Articulado Monitor",
                            Preco = 190.00m
                        });
                });

            modelBuilder.Entity("MinhaApi.Models.Produto", b =>
                {
                    b.HasOne("MinhaApi.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MinhaApi.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
